export const modules = [
  {
    id: "identity",
    owner: "成员 A",
    title: "账号与隐私",
    summary: "让每位求职者管理自己的登录、资料和数据。",
    features: ["注册", "登录", "个人资料", "修改密码", "导出数据", "注销账号"],
  },
  {
    id: "preparation",
    owner: "成员 B",
    title: "面试准备",
    summary: "把岗位案例、项目经历和练习目标连起来。",
    features: [
      "岗位案例",
      "准备计划",
      "经历素材",
      "简历深挖",
      "专项练习",
      "复习清单",
    ],
  },
  {
    id: "interview",
    owner: "成员 C",
    title: "面试进行",
    summary: "从文字回答逐步接入语音和面对面的面试体验。",
    features: [
      "创建面试",
      "文字作答",
      "澄清追问",
      "草稿与暂停",
      "流程推进",
      "3D 形象与视频",
    ],
  },
  {
    id: "assessment",
    owner: "成员 D",
    title: "评分与成长",
    summary: "每条评分都能追溯到回答中的证据。",
    features: [
      "评分规则",
      "证据评分",
      "二次校准",
      "单场复盘",
      "成长记录",
      "错题再练",
    ],
  },
  {
    id: "platform",
    owner: "负责人 E",
    title: "平台与交付",
    summary: "保持 AI、存储和部署有统一的入口。",
    features: [
      "持久化",
      "供应商配置",
      "文本模型网关",
      "语音识别与朗读",
      "原生实时对话",
      "部署与验收",
    ],
  },
] as const;
